import Head from 'next/head'
import '@/styles/Home.module.css'
import { Album } from '@/modules/Album'

export default function Home() {
  return (
    <>
      <Head>
        <title>NASA Pic of the Day</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/assets/favicon/favicon.ico" />
      </Head>
      <Album />
    </>
  )
}
